name: Commit Grammar

on:
  push:
    branches: [main]

jobs:
  commit_grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11
      - name: Download ANTLR 4.13.1
        working-directory: /tmp
        run: |
          wget https://www.antlr.org/download/antlr-4.13.1-complete.jar
      - name: Update grammar
        working-directory: kin/grammar
        run: |
          java -jar /tmp/antlr-4.13.1-complete.jar PBXProj.g4 -Dlanguage=Python3
      - name: Commit changes
        run: |
          git add kin/grammar
          git status
          if [ "$(git status --porcelain)" ]; then
            git config --global user.email "actions@users.noreply.github.com"
            git config --global user.name "Kin grammar bot"
            git commit -m "Update grammar"
            git push
          fi
